// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// 
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_naF9i-Kk80tZOK3Z_uiDTCArJlumGg',
    appId: '1:66203276647:web:9a7157f93d575e467b0bc2',
    messagingSenderId: '66203276647',
    projectId: 'flutter-404b5',
    authDomain: 'flutter-404b5.firebaseapp.com',
    storageBucket: 'flutter-404b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3cTdg9dTUawv6M0Ciif1M6g4wCNxhtM',
    appId: '1:66203276647:android:cdb915254f5b65e27b0bc2',
    messagingSenderId: '66203276647',
    projectId: 'flutter-404b5',
    storageBucket: 'flutter-404b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQP5T41a4Sg8fx60IzyLtwR5hRjyi3hjU',
    appId: '1:66203276647:ios:50bbeddbd3f341db7b0bc2',
    messagingSenderId: '66203276647',
    projectId: 'flutter-404b5',
    storageBucket: 'flutter-404b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp', // Alterado para o novo nome de pacote
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQP5T41a4Sg8fx60IzyLtwR5hRjyi3hjU',
    appId: '1:66203276647:ios:50bbeddbd3f341db7b0bc2',
    messagingSenderId: '66203276647',
    projectId: 'flutter-404b5',
    storageBucket: 'flutter-404b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp', // Alterado para o novo nome de pacote
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn_naF9i-Kk80tZOK3Z_uiDTCArJlumGg',
    appId: '1:66203276647:web:c518ab8ced1a66cd7b0bc2',
    messagingSenderId: '66203276647',
    projectId: 'flutter-404b5',
    authDomain: 'flutter-404b5.firebaseapp.com',
    storageBucket: 'flutter-404b5.firebasestorage.app',
  );
}
